{% set name = "shtns" %}
{% set version = "3.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://www.bitbucket.org/nschaeff/{{ name }}/downloads/{{ name }}-{{ version }}.tar.gz
    sha256: fd856ce6c57d7df4c403c1654b99da9a89ead93276b30dd48ba2c72acf463eaf
    folder: src

build:
  number: 3
  skip: true  # [win]

requirements:

  build:
    - {{ compiler('c') }}
    - make
  host:
    - fftw
    - numpy
    - python
  run:
    - fftw
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - shtns

about:
  home: https://nschaeff.bitbucket.io/shtns/
  license: CeCILL2.1
  license_file: LICENSE.txt
  summary: 'Fast spherical harmonic transform library aimed at high performance numerical simulations in spherical geometries.'

  description: |
    SHTns is a high performance library for Spherical
    Harmonic Transform written in C, aimed at numerical
    simulation (fluid flows, mhd, ...) in spherical
    geometries.

  doc_url: https://nschaeff.bitbucket.io/shtns/
  dev_url: https://nschaeff.bitbucket.io/shtns/

extra:
  recipe-maintainers:
    - peterspackman
