{% set name = "shtns" %}
{% set version = "3.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://www.bitbucket.org/nschaeff/{{ name }}/downloads/{{ name }}-{{ version }}.tar.gz
    sha256: 6609041baa2faa4199b1b09892748ffc0e5ee04d0c89fc17c34dc1c1e9193d41
    folder: src

build:
  number: 4
  skip: true  # [win]

requirements:

  build:
    - {{ compiler('c') }}
    - make
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - fftw
    - numpy
    - setuptools
    - pip
  run:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - python
    - fftw
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - shtns

about:
  home: https://nschaeff.bitbucket.io/shtns/
  license: CeCILL2.1
  license_file: LICENSE.txt
  summary: 'Fast spherical harmonic transform library aimed at high performance numerical simulations in spherical geometries.'

  description: |
    SHTns is a high performance library for Spherical
    Harmonic Transform written in C, aimed at numerical
    simulation (fluid flows, mhd, ...) in spherical
    geometries.

  doc_url: https://nschaeff.bitbucket.io/shtns/
  dev_url: https://nschaeff.bitbucket.io/shtns/

extra:
  recipe-maintainers:
    - peterspackman
